---
git:
  depth: 1
sudo: false
language: node_js
cache:
  directories:
  - node_modules

node_js:
 - stable
 - "4.0"
 - iojs
 - "0.10"
 - "0.12"

install:
  - echo "Skipping default npm install"

before_script:
- mv ./.npmrc ./.npmrc.bak
- npm install left-pad@0.0.3 
- mv ./.npmrc.bak ./.npmrc
- npm install

script:
- make test-ci

after_success:
 - ./scripts/travis/setup-git.sh
 - ./scripts/travis/merge-development-with-master.sh

notifications:
  slack: babeljs:5Wy4QX13KVkGy9CnU0rmvgeK
